name: AI Market Radar

on:

  schedule:
    - cron: "0 */4 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  scan-market:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install yfinance pandas numpy requests feedparser

      - name: Run AI Market Radar
        run: |
          cd backend
          python news_scanner.py

      - name: Commit JSON Updates
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git pull origin main --no-rebase

          git add news_data.json

          git commit -m "Update AI Market Radar" || echo "No changes"

          git push